name: cron

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: fetch IP_URL_1
        run: bash -c "$IP_URL_1"
        env:
          IP_URL_1: ${{ secrets.IP_URL_1 }}
      
      - name: fetch IP_URL_2
        run: bash -c "$IP_URL_2"
        env:
          IP_URL_2: ${{ secrets.IP_URL_2 }}
        
      - name: fetch IMG_URL
        run: curl -s -X GET "$IMG_URL"
        env:
          IMG_URL: ${{ secrets.IMG_URL }}

      - name: fetch VIDEO_URL
        run: curl -s -X GET "$VIDEO_URL"
        env:
          VIDEO_URL: ${{ secrets.VIDEO_URL }}

      - name: fetch TIME_URL
        run: curl -s -X GET "$TIME_URL"
        env:
          TIME_URL: ${{ secrets.TIME_URL }}

      - name: fetch SCRAPER_URL
        run: curl -s -X GET "$SCRAPER_URL"
        env:
          SCRAPER_URL: ${{ secrets.SCRAPER_URL }}      
