name: cron

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Run Command 1
        run: date && bash -c "$CMD_1" && echo && date
        env:
          CMD_1: ${{ secrets.CMD_1 }}
      - name: Run Command 2
        run: date && bash -c "$CMD_2" && echo && date
        env:
          CMD_2: ${{ secrets.CMD_2 }}
      - name: Run Command 3
        run: date && bash -c "$CMD_3" && echo && date
        env:
          CMD_3: ${{ secrets.CMD_3 }}
      - name: Run Command 4
        run: date && bash -c "$CMD_4" && echo && date
        env:
          CMD_4: ${{ secrets.CMD_4 }}
      - name: Run Command 5
        run: date && bash -c "$CMD_5" && echo && date
        env:
          CMD_5: ${{ secrets.CMD_5 }}
      - name: Run Command 6
        run: date && bash -c "$CMD_6" && echo && date
        env:
          CMD_6: ${{ secrets.CMD_6 }}
      - name: Run Command 7
        run: date && bash -c "$CMD_1" && echo && date
        env:
          CMD_7: ${{ secrets.CMD_17 }}
      - name: Run Command 8
        run: date && bash -c "$CMD_8" && echo && date
        env:
          CMD_8: ${{ secrets.CMD_8 }}
